name: appse
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.3
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.3
  firebase_core: 2.25.3
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  font_awesome_flutter: ^10.7.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: 4.6.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  lottie: ^3.0.0
  onboarding_intro_screen: ^0.0.8
  path_provider: ^2.1.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: "Comfortaa"
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
  uses-material-design: true
  assets:
    - assets/lotties/
